spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db
    username: hiba
    password: hiba

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # ← AJOUTER CETTE LIGNE

  sql:
    init:
      mode: always                            # ← AJOUTER
      data-locations: classpath:data-docker.sql  # ← AJOUTER

  kafka:
    bootstrap-servers: kafka:9092

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka123@service-registry:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: user-service
    instance-id: user-service:8081