spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_service
    username: postgres
    password: akb

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.transport.subscription: DEBUG
    org.springframework.web: DEBUG

payment:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:sk_test_mock_key}

