spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_service
    username: postgres
    password: akb

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.transport.subscription: INFO

payment:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}

scheduler:
  renewal:
    enabled: true
    cron: 0 0 0 * * *

